version: "3.11"
services:
  app:
    build:
      context: .
      args:
        - DEV=true
    ports:
      - "9000:8000"
    volumes:
      - ./app:/app
      - static-data:/vol/web
    environment:
      - DB_HOST=db
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - SECRET_KEY=${DJANGO_SECRET_KEY}
      - ALLOWED_HOSTS=${DJANGO_ALLOWED_HOSTS}
      - PYTHONPATH=/app
    depends_on:
      - db
      - redis

  db:
    image: postgres:16.3-alpine3.20
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}

  redis: # Redis
    image: redis:alpine
    ports:
      - "6379:6379"

  proxy:
    build:
      context: ./proxy
    restart: always
    depends_on:
      - app
    ports:
      - "80:80"  # Public port mapping
    volumes:
      - static-data:/vol/static
    environment:
      - LISTEN_PORT=80  # Nginx will listen on port 80
      - APP_HOST=app
      - APP_PORT=9000  # Django app will run on port 9000 internally

volumes:
  postgres-data:
  static-data: